### PR TITLE
Clarify we don't provide SOC reports

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Review by dirkx — COMMENTED** [review]
:) +1

**Review by dirkx — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Review by clr-apache — COMMENTED** [review]
It would be useful for readers of this who are not already domain experts to have the actual names instead of just e.g. STIG. Perhaps even an https://stig.whatever so first time readers could easily find the relevant high level view.

**Comment by raboof** [comment]
> It would be useful for readers of this who are not already domain experts to have the actual names instead of just e.g. STIG. Perhaps even an https://stig.whatever so first time readers could easily find the relevant high level view.

Good idea, added links in #39. I kept the abbreviations as I think those are often actually more recognizable than the full names.

**Comment by clr-apache** [comment]
Perfect. Thanks.

**Pull request merged**
